### ISSUE TITLE
qemu-system-x86_64: CPU feature check not found

### ISSUE THREAD

**Issue by lionelstellar** [PanQL/zircon#1]
make run报这个错是为啥
`./scripts/run-zircon-x64 -z ./out/legacy-image-x64.zbi -t ./out/multiboot.bin
CMDLINE: TERM=xterm-256color kernel.serial=legacy kernel.entropy-mixin=38c15aaba825a204b70076df492ae6195757ee560ecbef75c471d9ace05c2a3e kernel.halt-on-panic=true + exec qemu-system-x86_64 -kernel /home/src/zircon/./out/multiboot.bin -initrd /home/src/zircon/./out/legacy-image-x64.zbi -m 2048 -nographic -net none -smp 4,threads=2 -machine q35 -device isa-debug-exit,iobase=0xf4,iosize=0x04 -cpu Haswell,+smap,-check,-fsgsbase -append 'TERM=xterm-256color kernel.serial=legacy kernel.entropy-mixin=38c15aaba825a204b70076df492ae6195757ee560ecbef75c471d9ace05c2a3e` kernel.halt-on-panic=true '
qemu-system-x86_64: CPU feature check not found
Makefile:8: recipe for target 'run' failed
make: *** [run] Error 1`

**Comment by PanQL** [comment]
请问你使用的qemu版本是多少？

**Comment by lionelstellar** [comment]
QEMU emulator version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.42), Copyright (c) 2003-2008 Fabrice Bellard

**Comment by lionelstellar** [comment]
更新到了qemu 4.2.0可以运行了😂

**Comment by PanQL** [comment]
是的，我用的也是最新版。官方提供的修改版qemu似乎版本也很高。
